services:
  server:
    image: deno-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    develop:
      watch:
        - action: rebuild
          path: .
